<a href="https://colab.research.google.com/github/kavks03-bit/E-COMMERCE-ANALYSIS-INTELLIGENT-SYSTEM/blob/main/MINI_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#===============================================
#E_COMMERCE ANALYSIS INTELLIGENT SYSTEM
#===============================================
#Project Flow:
# Data Generation
#       ↓
# Data Cleaning
#       ↓
# EDA
#       ↓
# Sales Analytics
#       ↓
# Customer Analytics
#       ↓
# RFM Analysis
#       ↓
# Customer Segmentation
#       ↓
# K-Means Clustering
#       ↓
# Interactive Analysis
#       ↓
# Business Insights
# ============================================================

#1. INSTALL / IMPORT LIBRARIES
# ============================================================

#!pip install -q pandas numpy plotly scikit-learn ipywidgets

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

import ipywidgets as widgets
from IPython.display import display, clear_output

import warnings
warnings.filterwarnings("ignore")


# ============================================================
# 2. CREATE E-COMMERCE DATASET
# ============================================================

np.random.seed(42)

# Number of transactions
n_transactions = 10000

# Customer IDs
customer_ids = np.random.randint(
    1001,
    2001,
    n_transactions
)

# Products
products = [
    "Laptop",
    "Smartphone",
    "Headphones",
    "Smartwatch",
    "Tablet",
    "Keyboard",
    "Mouse",
    "Monitor",
    "Camera",
    "Speaker"
]

# Product categories
categories = {
    "Laptop": "Electronics",
    "Smartphone": "Electronics",
    "Headphones": "Accessories",
    "Smartwatch": "Wearables",
    "Tablet": "Electronics",
    "Keyboard": "Accessories",
    "Mouse": "Accessories",
    "Monitor": "Electronics",
    "Camera": "Electronics",
    "Speaker": "Audio"
}

# Countries
countries = [
    "India",
    "USA",
    "UK",
    "Germany",
    "Canada",
    "Australia"
]

# Generate product
product_data = np.random.choice(
    products,
    n_transactions
)

# Generate quantity
quantity_data = np.random.randint(
    1,
    6,
    n_transactions
)

# Generate prices
price_data = np.random.uniform(
    20,
    1500,
    n_transactions
)

# Generate dates
date_data = pd.date_range(
    start="2025-01-01",
    end="2025-12-31",
    periods=n_transactions
)

# Create DataFrame
df = pd.DataFrame({

    "Customer_ID": customer_ids,

    "Product": product_data,

    "Category": [
        categories[p]
        for p in product_data
    ],

    "Country": np.random.choice(
        countries,
        n_transactions
    ),

    "Quantity": quantity_data,

    "UnitPrice": price_data,

    "PurchaseDate": date_data
})


# ============================================================
# 3. CREATE REVENUE
# ============================================================

df["Revenue"] = (
    df["Quantity"] *
    df["UnitPrice"]
)


# ============================================================
# 4. ADD ADDITIONAL CUSTOMER INFORMATION
# ============================================================

customer_gender = {}

for customer in df["Customer_ID"].unique():

    customer_gender[customer] = np.random.choice(
        ["Male", "Female"],
        p=[0.55, 0.45]
    )

df["Gender"] = df["Customer_ID"].map(
    customer_gender
)


# ============================================================
# 5. DISPLAY DATASET
# ============================================================

print("=" * 60)
print("ECOMMERCE DATASET")
print("=" * 60)

print("Dataset Shape:")
print(df.shape)

print("First ten records:")
print(df.head(10))


# ============================================================
# 6. DATA INFORMATION
# ============================================================

print("=" * 60)
print("DATA INFORMATION")
print("=" * 60)

df.info()


# ============================================================
# 7. MISSING VALUES
# ============================================================

print("=" * 60)
print("MISSING VALUES")
print("=" * 60)

missing_values = df.isnull().sum()

display(
    missing_values.to_frame(
        "Missing values"
    )
)


# ============================================================
# 8. CHECK DUPLICATES
# ============================================================

print("=" * 60)
print("CHECK DUPLICATES")
print("=" * 60)

duplicates = df.duplicated().sum()

print(
    "Number of duplicate records:",
    duplicates
)


# ============================================================
# 9. DATA CLEANING
# ============================================================

df = df.drop_duplicates()

df = df[
    (df["Quantity"] > 0) &
    (df["UnitPrice"] > 0)
]

df["PurchaseDate"] = pd.to_datetime(
    df["PurchaseDate"]
)

df["Revenue"] = (
    df["Quantity"] *
    df["UnitPrice"]
)


# ============================================================
# 10. DATE FEATURES
# ============================================================

df["Year"] = (
    df["PurchaseDate"].dt.year
)

df["Month"] = (
    df["PurchaseDate"].dt.month
)

df["MonthName"] = (
    df["PurchaseDate"]
    .dt.strftime("%B")
)

df["Day"] = (
    df["PurchaseDate"].dt.day
)

df["Weekday"] = (
    df["PurchaseDate"].dt.day_name()
)


# ============================================================
# 11. BUSINESS KPIs
# ============================================================

total_revenue = df["Revenue"].sum()

total_customers = df[
    "Customer_ID"
].nunique()

total_transactions = len(df)

total_units = df[
    "Quantity"
].sum()

average_transaction_value = (
    df["Revenue"].mean()
)

print("=" * 60)
print("BUSINESS KPIs")
print("=" * 60)

print(
    f"Total Revenue              : ${total_revenue:,.2f}"
)

print(
    f"Total Customers            : {total_customers:,}"
)

print(
    f"Total Transactions         : {total_transactions:,}"
)

print(
    f"Total Units Sold           : {total_units:,}"
)

print(
    f"Average Transaction Value  : ${average_transaction_value:,.2f}"
)


# ============================================================
# 12. MONTHLY REVENUE
# ============================================================

monthly_revenue = (
    df.groupby("MonthName")["Revenue"]
    .sum()
    .reset_index()
)

month_order = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]

monthly_revenue["MonthName"] = pd.Categorical(
    monthly_revenue["MonthName"],
    categories=month_order,
    ordered=True
)

monthly_revenue = monthly_revenue.sort_values(
    "MonthName"
)

fig = px.line(
    monthly_revenue,
    x="MonthName",
    y="Revenue",
    markers=True,
    title="Monthly Revenue Trend"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Revenue"
)

fig.show()


# ============================================================
# 13. PRODUCT REVENUE
# ============================================================

product_revenue = (
    df.groupby("Product")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

fig = px.bar(
    product_revenue,
    x="Revenue",
    y="Product",
    orientation="h",
    title="Revenue by Product"
)

fig.show()


# ============================================================
# 14. PRODUCT QUANTITY ANALYSIS
# ============================================================

product_quantity = (
    df.groupby("Product")["Quantity"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

fig = px.bar(
    product_quantity,
    x="Product",
    y="Quantity",
    title="Units Sold by Product"
)

fig.show()


# ============================================================
# 15. CATEGORY ANALYSIS
# ============================================================

category_revenue = (
    df.groupby("Category")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

fig = px.pie(
    category_revenue,
    names="Category",
    values="Revenue",
    hole=0.4,
    title="Revenue by Category"
)

fig.show()


# ============================================================
# 16. COUNTRY ANALYSIS
# ============================================================

country_revenue = (
    df.groupby("Country")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

fig = px.bar(
    country_revenue,
    x="Country",
    y="Revenue",
    title="Revenue by Country"
)

fig.show()


# ============================================================
# 17. CUSTOMER REVENUE
# ============================================================

customer_revenue = (
    df.groupby("Customer_ID")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

print("=" * 60)
print("TOP 10 CUSTOMERS")
print("=" * 60)

display(
    customer_revenue.head(10)
)


# ============================================================
# 18. TOP 10 CUSTOMERS VISUALIZATION
# ============================================================

top_customers = customer_revenue.head(10)

fig = px.bar(
    top_customers,
    x="Customer_ID",
    y="Revenue",
    title="Top 10 Customers by Revenue"
)

fig.show()


# ============================================================
# 19. CUSTOMER PURCHASE FREQUENCY
# ============================================================

customer_frequency = (
    df.groupby("Customer_ID")
    .size()
    .reset_index(
        name="Frequency"
    )
)

fig = px.histogram(
    customer_frequency,
    x="Frequency",
    nbins=30,
    title="Customer Purchase Frequency"
)

fig.show()


# ============================================================
# 20. RFM ANALYSIS
# ============================================================

print("=" * 60)
print("RFM ANALYSIS")
print("=" * 60)


# Reference date
reference_date = (
    df["PurchaseDate"].max()
    + pd.Timedelta(days=1)
)


# Calculate RFM
rfm = df.groupby(
    "Customer_ID"
).agg({

    "PurchaseDate":
        lambda x:
        (
            reference_date -
            x.max()
        ).days,

    "Customer_ID":
        "count",

    "Revenue":
        "sum"
})


# Rename columns
rfm.columns = [
    "Recency",
    "Frequency",
    "Monetary"
]

rfm = rfm.reset_index()


print("\n========== RFM VALUES ==========")

display(
    rfm.head(10)
)


# ============================================================
# RFM SCORING
# ============================================================

# Recency
# Lower Recency is better
rfm["R_Score"] = pd.qcut(
    rfm["Recency"].rank(method="first"),
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)


# Frequency
# Higher Frequency is better
rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)


# Monetary
# Higher Monetary value is better
rfm["M_Score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)


# Combine R, F and M scores
rfm["RFM_Score"] = (
    rfm["R_Score"].astype(str)
    + rfm["F_Score"].astype(str)
    + rfm["M_Score"].astype(str)
)


print("\n========== RFM SCORES ==========")

display(
    rfm[
        [
            "Customer_ID",
            "Recency",
            "Frequency",
            "Monetary",
            "R_Score",
            "F_Score",
            "M_Score",
            "RFM_Score"
        ]
    ].head(10)
)


# ============================================================
# 21. CUSTOMER SEGMENTS USING RFM
# ============================================================

def assign_segment(row):

    if (
        row["R_Score"] >= 4
        and row["F_Score"] >= 4
        and row["M_Score"] >= 4
    ):

        return "Champions"

    elif (
        row["R_Score"] >= 4
        and row["F_Score"] >= 3
    ):

        return "Loyal Customers"

    elif (
        row["R_Score"] >= 4
        and row["M_Score"] >= 3
    ):

        return "Potential Loyalists"

    elif (
        row["R_Score"] <= 2
        and row["F_Score"] >= 3
    ):

        return "At Risk"

    elif (
        row["R_Score"] <= 2
        and row["M_Score"] >= 3
    ):

        return "High Value At Risk"

    elif (
        row["R_Score"] <= 2
        and row["F_Score"] <= 2
    ):

        return "Lost Customers"

    else:

        return "Regular Customers"


rfm["Segment"] = rfm.apply(
    assign_segment,
    axis=1
)


print("\n========== CUSTOMER SEGMENTS ==========")

segment_count = (
    rfm["Segment"]
    .value_counts()
    .reset_index()
)

segment_count.columns = [
    "Segment",
    "CustomerCount"
]

display(
    segment_count
)


# ============================================================
# 22. SEGMENT DISTRIBUTION
# ============================================================

fig = px.pie(
    segment_count,
    names="Segment",
    values="CustomerCount",
    hole=0.4,
    title="Customer Segment Distribution"
)

fig.show()


# ============================================================
# 23. 3D RFM VISUALIZATION
# ============================================================

fig = px.scatter_3d(
    rfm,
    x="Recency",
    y="Frequency",
    z="Monetary",
    color="Segment",

    hover_data=[
        "Customer_ID",
        "RFM_Score"
    ],

    title="3D RFM Customer Analysis"
)

fig.update_layout(
    scene=dict(
        xaxis_title="Recency",
        yaxis_title="Frequency",
        zaxis_title="Monetary"
    )
)

fig.show()

# ============================================================
# 24. REVENUE BY CUSTOMER SEGMENT
# ============================================================

segment_revenue = (
    rfm.groupby("Segment")["Monetary"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

fig = px.bar(
    segment_revenue,
    x="Segment",
    y="Monetary",
    title="Revenue Contribution by Customer Segment"
)

fig.show()


# ============================================================
# 25. CUSTOMER BEHAVIOUR
# ============================================================

fig = px.scatter(
    rfm,
    x="Frequency",
    y="Monetary",
    size="Monetary",
    color="Segment",

    hover_data=[
        "Customer_ID",
        "Recency",
        "RFM_Score"
    ],

    title="Customer Frequency vs Spending"
)

fig.show()


# ============================================================
# 26. RFM 3D VISUALIZATION
# ============================================================

fig = px.scatter_3d(
    rfm,
    x="Recency",
    y="Frequency",
    z="Monetary",
    color="Segment",

    hover_data=[
        "Customer_ID"
    ],

    title="3D RFM Customer Analysis"
)

fig.update_layout(
    scene=dict(
        xaxis_title="Recency",
        yaxis_title="Frequency",
        zaxis_title="Monetary"
    )
)

fig.show()


# ============================================================
# 27. K-MEANS CUSTOMER SEGMENTATION
# ============================================================

print("=" * 60)
print("K-MEANS CUSTOMER SEGMENTATION")
print("=" * 60)


# ------------------------------------------------------------
# Select features for K-Means
# ------------------------------------------------------------

features = rfm[
    [
        "Recency",
        "Frequency",
        "Monetary"
    ]
]


# ------------------------------------------------------------
# Standardize the features
# ------------------------------------------------------------

scaler = StandardScaler()

scaled_features = scaler.fit_transform(
    features
)


# ------------------------------------------------------------
# Create K-Means model
# ------------------------------------------------------------

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)


# ------------------------------------------------------------
# Train K-Means
# ------------------------------------------------------------

kmeans.fit(
    scaled_features
)


# ------------------------------------------------------------
# Assign cluster to each customer
# ------------------------------------------------------------

rfm["Cluster"] = kmeans.labels_


print("\n========== K-MEANS RESULTS ==========")

display(
    rfm[
        [
            "Customer_ID",
            "Recency",
            "Frequency",
            "Monetary",
            "Cluster"
        ]
    ].head(10)
)


# ============================================================
# 27.1 K-MEANS CLUSTER VISUALIZATION
# ============================================================

fig = px.scatter_3d(
    rfm,
    x="Recency",
    y="Frequency",
    z="Monetary",
    color="Cluster",

    hover_data=[
        "Customer_ID",
        "Segment",
        "RFM_Score"
    ],

    title="K-Means Customer Segmentation - 3D"
)

fig.update_layout(
    scene=dict(
        xaxis_title="Recency",
        yaxis_title="Frequency",
        zaxis_title="Monetary"
    )
)

fig.show()

# ============================================================
# 28. CLUSTER SUMMARY
# ============================================================

print("=" * 60)
print("K-MEANS CLUSTER SUMMARY")
print("=" * 60)


cluster_summary = (
    rfm.groupby("Cluster")
    .agg({
        "Recency": "mean",
        "Frequency": "mean",
        "Monetary": "mean",
        "Customer_ID": "count"
    })
    .round(2)
)


cluster_summary.rename(
    columns={
        "Customer_ID": "Customers"
    },
    inplace=True
)


print("Cluster Summary:")

display(
    cluster_summary
)


# ============================================================
# 29. K-MEANS 3D VISUALIZATION
# ============================================================

fig = px.scatter_3d(
    rfm,
    x="Recency",
    y="Frequency",
    z="Monetary",
    color="Cluster",

    hover_data=[
        "Customer_ID",
        "Segment"
    ],

    title="K-Means Customer Clusters"
)

fig.update_layout(
    scene=dict(
        xaxis_title="Recency",
        yaxis_title="Frequency",
        zaxis_title="Monetary"
    )
)

fig.show()


# ============================================================
# 30. FIND AT-RISK CUSTOMERS
# ============================================================

at_risk = rfm[
    rfm["Segment"] == "At Risk"
]


print("=" * 60)
print("AT-RISK CUSTOMERS")
print("=" * 60)

print(
    "Number of At-Risk Customers:",
    len(at_risk)
)


display(
    at_risk[
        [
            "Customer_ID",
            "Recency",
            "Frequency",
            "Monetary",
            "RFM_Score"
        ]
    ]
    .sort_values(
        "Monetary",
        ascending=False
    )
    .head(20)
)


# ============================================================
# 31. CHAMPION CUSTOMERS
# ============================================================

champions = rfm[
    rfm["Segment"] == "Champions"
]


print("=" * 60)
print("CHAMPION CUSTOMERS")
print("=" * 60)

print(
    "Number of Champions:",
    len(champions)
)


display(
    champions[
        [
            "Customer_ID",
            "Recency",
            "Frequency",
            "Monetary",
            "RFM_Score"
        ]
    ]
    .sort_values(
        "Monetary",
        ascending=False
    )
    .head(20)
)


# ============================================================
# 32. INTERACTIVE PRODUCT ANALYSIS
# ============================================================

print("=" * 60)
print("INTERACTIVE PRODUCT ANALYSIS")
print("=" * 60)


product_dropdown = widgets.Dropdown(

    options=[
        "All Products"
    ] +
    sorted(
        df["Product"].unique()
    ),

    description="Product:",

    style={
        "description_width": "initial"
    }
)


product_output = widgets.Output()


def product_analysis(change):

    with product_output:

        clear_output(wait=True)

        selected_product = change["new"]


        # ----------------------------------------------------
        # Filter data
        # ----------------------------------------------------

        if selected_product == "All Products":

            temp = df.copy()

        else:

            temp = df[
                df["Product"] == selected_product
            ]


        # ----------------------------------------------------
        # KPIs
        # ----------------------------------------------------

        revenue = temp[
            "Revenue"
        ].sum()

        quantity = temp[
            "Quantity"
        ].sum()

        transactions = len(temp)


        print(
            f"Product: {selected_product}"
        )

        print(
            f"Revenue: ${revenue:,.2f}"
        )

        print(
            f"Units Sold: {quantity:,}"
        )

        print(
            f"Transactions: {transactions:,}"
        )


        # ----------------------------------------------------
        # Monthly analysis
        # ----------------------------------------------------

        monthly = (
            temp.groupby(
                "MonthName"
            )["Revenue"]
            .sum()
            .reset_index()
        )


        monthly["MonthName"] = pd.Categorical(
            monthly["MonthName"],
            categories=month_order,
            ordered=True
        )


        monthly = monthly.sort_values(
            "MonthName"
        )


        fig = px.line(
            monthly,
            x="MonthName",
            y="Revenue",
            markers=True,
            title=f"Monthly Revenue - {selected_product}"
        )


        fig.show()


product_dropdown.observe(
    product_analysis,
    names="value"
)


display(
    product_dropdown
)

display(
    product_output
)


# ============================================================
# 33. INTERACTIVE COUNTRY ANALYSIS
# ============================================================

print("=" * 60)
print("INTERACTIVE COUNTRY ANALYSIS")
print("=" * 60)


country_dropdown = widgets.Dropdown(

    options=[
        "All Countries"
    ] +
    sorted(
        df["Country"].unique()
    ),

    description="Country:",

    style={
        "description_width": "initial"
    }
)


country_output = widgets.Output()


def country_analysis(change):

    with country_output:

        clear_output(wait=True)

        selected_country = change["new"]


        # ----------------------------------------------------
        # Filter data
        # ----------------------------------------------------

        if selected_country == "All Countries":

            temp = df.copy()

        else:

            temp = df[
                df["Country"] == selected_country
            ]


        # ----------------------------------------------------
        # KPIs
        # ----------------------------------------------------

        revenue = temp[
            "Revenue"
        ].sum()

        customers = temp[
            "Customer_ID"
        ].nunique()

        transactions = len(temp)


        print(
            f"Country: {selected_country}"
        )

        print(
            f"Revenue: ${revenue:,.2f}"
        )

        print(
            f"Customers: {customers:,}"
        )

        print(
            f"Transactions: {transactions:,}"
        )


        # ----------------------------------------------------
        # Category analysis
        # ----------------------------------------------------

        category = (
            temp.groupby(
                "Category"
            )["Revenue"]
            .sum()
            .reset_index()
        )


        fig = px.bar(
            category,
            x="Category",
            y="Revenue",
            title=f"Category Performance - {selected_country}"
        )


        fig.show()


country_dropdown.observe(
    country_analysis,
    names="value"
)


display(
    country_dropdown
)

display(
    country_output
)


# ============================================================
# 34. INTERACTIVE CUSTOMER SEGMENT FILTER
# ============================================================

print("=" * 60)
print("CUSTOMER SEGMENT EXPLORER")
print("=" * 60)


segment_dropdown = widgets.Dropdown(

    options=[
        "All Segments"
    ] +
    sorted(
        rfm["Segment"].unique()
    ),

    description="Segment:",

    style={
        "description_width": "initial"
    }
)


segment_output = widgets.Output()


def segment_analysis(change):

    with segment_output:

        clear_output(wait=True)

        selected_segment = change["new"]


        # ----------------------------------------------------
        # Filter data
        # ----------------------------------------------------

        if selected_segment == "All Segments":

            temp = rfm.copy()

        else:

            temp = rfm[
                rfm["Segment"] == selected_segment
            ]


        # ----------------------------------------------------
        # Segment KPIs
        # ----------------------------------------------------

        print(
            f"Segment: {selected_segment}"
        )

        print(
            f"Customers: {len(temp):,}"
        )

        print(
            f"Average Recency: "
            f"{temp['Recency'].mean():.2f} days"
        )

        print(
            f"Average Frequency: "
            f"{temp['Frequency'].mean():.2f}"
        )

        print(
            f"Total Revenue: "
            f"${temp['Monetary'].sum():,.2f}"
        )


        # ----------------------------------------------------
        # Customer table
        # ----------------------------------------------------

        display(
            temp[
                [
                    "Customer_ID",
                    "Recency",
                    "Frequency",
                    "Monetary",
                    "RFM_Score",
                    "Segment"
                ]
            ]
            .sort_values(
                "Monetary",
                ascending=False
            )
            .head(20)
        )


segment_dropdown.observe(
    segment_analysis,
    names="value"
)


display(
    segment_dropdown
)

display(
    segment_output
)


# ============================================================
# 35. AUTOMATIC BUSINESS INSIGHTS
# ============================================================

print("=" * 60)
print("AUTOMATIC BUSINESS INSIGHTS")
print("=" * 60)


# ------------------------------------------------------------
# Best Product
# ------------------------------------------------------------

best_product = (
    df.groupby("Product")["Revenue"]
    .sum()
    .idxmax()
)


# ------------------------------------------------------------
# Best Country
# ------------------------------------------------------------

best_country = (
    df.groupby("Country")["Revenue"]
    .sum()
    .idxmax()
)


# ------------------------------------------------------------
# Best Category
# ------------------------------------------------------------

best_category = (
    df.groupby("Category")["Revenue"]
    .sum()
    .idxmax()
)


# ------------------------------------------------------------
# Largest Customer Segment
# ------------------------------------------------------------

largest_segment = (
    rfm["Segment"]
    .value_counts()
    .idxmax()
)


print(
    f"Best Product    : {best_product}"
)

print(
    f"Best Country    : {best_country}"
)

print(
    f"Best Category   : {best_category}"
)

print(
    f"Largest Segment : {largest_segment}"
)


# ============================================================
# 36. FINAL CUSTOMER INTELLIGENCE REPORT
# ============================================================

print("=" * 60)
print("FINAL E-COMMERCE CUSTOMER INTELLIGENCE REPORT")
print("=" * 60)

print()

print(
    f"Total Revenue       : ${total_revenue:,.2f}"
)

print(
    f"Total Customers     : {total_customers:,}"
)

print(
    f"Total Transactions  : {total_transactions:,}"
)

print(
    f"Total Units Sold    : {total_units:,}"
)

print(
    f"Average Order Value : ${average_transaction_value:,.2f}"
)

print()

print(
    f"Best Product        : {best_product}"
)

print(
    f"Best Country        : {best_country}"
)

print(
    f"Best Category       : {best_category}"
)

print(
    f"Largest Segment     : {largest_segment}"
)

print()

print(
    "Customer Intelligence Analysis Completed."
)

print("=" * 60)

============================================================
ECOMMERCE DATASET
============================================================
Dataset Shape:
(10000, 9)
First ten records:
   Customer_ID     Product     Category  Country  Quantity    UnitPrice  \
0         1103     Speaker        Audio  Germany         5   421.220516
1         1436       Mouse  Accessories  Germany         5  1060.482352
2         1861    Keyboard  Accessories      USA         3  1394.133606
3         1271      Laptop  Electronics  Germany         5  1035.704409
4         1107     Monitor  Electronics       UK         4  1028.042058
5         1072  Smartphone  Electronics    India         2   351.183402
6         1701      Tablet  Electronics  Germany         2   811.992696
7         1021      Camera  Electronics       UK         4   852.533809
8         1615     Monitor  Electronics       UK         5  1056.191752
9         1122  Smartphone  Electronics      USA         1  1495.295746

                   PurchaseDate      Revenue  Gender
0 2025-01-01 00:00:00.000000000  2106.102579  Female
1 2025-01-01 00:52:25.274527452  5302.411762  Female
2 2025-01-01 01:44:50.549054905  4182.400817    Male
3 2025-01-01 02:37:15.823582358  5178.522043  Female
4 2025-01-01 03:29:41.098109810  4112.168232  Female
5 2025-01-01 04:22:06.372637263   702.366804  Female
6 2025-01-01 05:14:31.647164716  1623.985393    Male
7 2025-01-01 06:06:56.921692169  3410.135234  Female
8 2025-01-01 06:59:22.196219621  5280.958762    Male
9 2025-01-01 07:51:47.470747074  1495.295746    Male
============================================================
DATA INFORMATION
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Customer_ID   10000 non-null  int64
 1   Product       10000 non-null  object
 2   Category      10000 non-null  object
 3   Country       10000 non-null  object
 4   Quantity      10000 non-null  int64
 5   UnitPrice     10000 non-null  float64
 6   PurchaseDate  10000 non-null  datetime64[ns]
 7   Revenue       10000 non-null  float64
 8   Gender        10000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 703.3+ KB
============================================================
MISSING VALUES
============================================================

              Missing values
Customer_ID                0
Product                    0
Category                   0
Country                    0
Quantity                   0
UnitPrice                  0
PurchaseDate               0
Revenue                    0
Gender                     0

============================================================
CHECK DUPLICATES
============================================================
Number of duplicate records: 0
============================================================
BUSINESS KPIs
============================================================
Total Revenue              : $22,779,760.07
Total Customers            : 1,000
Total Transactions         : 10,000
Total Units Sold           : 30,054
Average Transaction Value  : $2,277.98

============================================================
TOP 10 CUSTOMERS
============================================================

   Customer_ID       Revenue
0         1073  63411.273057
1         1726  54753.396789
2         1936  52605.319195
3         1758  51151.289868
4         1889  50105.289656
5         1283  49445.197724
6         1929  49419.019015
7         1659  48800.421761
8         1130  47903.580832
9         1891  46723.822640

============================================================
RFM ANALYSIS
============================================================

========== RFM VALUES ==========

   Customer_ID  Recency  Frequency      Monetary
0         1001       19         16  39084.768665
1         1002        6          9  12197.085893
2         1003       33          9  15908.271449
3         1004       77          5   5563.067711
4         1005       92          9  28535.929546
5         1006       87          7  14408.859252
6         1007       36         11  32982.129111
7         1008        5         13  22353.175432
8         1009        8          6  15437.505443
9         1010       19         13  30114.102865

========== RFM SCORES ==========

,Customer_ID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score
0,1001,19,16,39084.768665,4,5,5,455
1,1002,6,9,12197.085893,5,2,1,521
2,1003,33,9,15908.271449,3,2,2,322
3,1004,77,5,5563.067711,1,1,1,111
4,1005,92,9,28535.929546,1,2,4,124
5,1006,87,7,14408.859252,1,1,1,111
6,1007,36,11,32982.129111,2,3,5,235
7,1008,5,13,22353.175432,5,4,3,543
8,1009,8,6,15437.505443,5,1,2,512
9,1010,19,13,30114.102865,4,4,4,444

========== CUSTOMER SEGMENTS ==========

               Segment  CustomerCount
0    Regular Customers            286
1              At Risk            195
2       Lost Customers            163
3            Champions            153
4      Loyal Customers            124
5   High Value At Risk             42
6  Potential Loyalists             37

============================================================
K-MEANS CUSTOMER SEGMENTATION
============================================================

========== K-MEANS RESULTS ==========

   Customer_ID  Recency  Frequency      Monetary  Cluster
0         1001       19         16  39084.768665        2
1         1002        6          9  12197.085893        0
2         1003       33          9  15908.271449        0
3         1004       77          5   5563.067711        0
4         1005       92          9  28535.929546        1
5         1006       87          7  14408.859252        0
6         1007       36         11  32982.129111        1
7         1008        5         13  22353.175432        1
8         1009        8          6  15437.505443        0
9         1010       19         13  30114.102865        2

============================================================
K-MEANS CLUSTER SUMMARY
============================================================
Cluster Summary:

         Recency  Frequency  Monetary  Customers
Cluster
0          36.02       6.91  14241.54        296
1          29.52      10.45  23794.62        407
2          23.20      14.37  34813.64        226
3         142.49       6.41  14253.12         71

============================================================
AT-RISK CUSTOMERS
============================================================
Number of At-Risk Customers: 195

     Customer_ID  Recency  Frequency      Monetary RFM_Score
647         1648      131         12  46115.217539       145
419         1420       52         15  44527.216319       255
155         1156       59         14  44483.714827       255
475         1476       66         13  43324.466009       155
663         1664       44         17  43244.668917       255
539         1540       47         14  41827.022296       255
936         1937       45         15  41556.481270       255
961         1962       45         15  40764.998238       255
110         1111       37         17  40096.200820       255
219         1220       55         14  39605.811312       255
480         1481       43         12  39584.919187       245
75          1076       48         12  39219.351731       245
899         1900       53         12  38855.205051       245
603         1604       45         10  38730.081910       235
946         1947       35         16  37666.790017       255
832         1833       94         14  37558.492389       155
550         1551       42         12  37116.197081       245
675         1676       73         13  36920.064060       155
851         1852       38         13  36734.029048       255
569         1570       92          9  36373.182100       135

============================================================
CHAMPION CUSTOMERS
============================================================
Number of Champions: 153

     Customer_ID  Recency  Frequency      Monetary RFM_Score
72          1073       15         19  63411.273057       455
935         1936       11         18  52605.319195       455
757         1758        2         17  51151.289868       555
888         1889        8         13  50105.289656       555
282         1283        3         18  49445.197724       555
928         1929        2         21  49419.019015       555
129         1130       10         17  47903.580832       455
914         1915        1         18  46681.723076       555
128         1129        4         16  45305.780237       555
669         1670       18         16  45037.777831       455
225         1226        2         13  44626.540215       545
821         1822       13         18  44609.538749       455
502         1503        7         12  43273.378492       545
160         1161        1         17  42761.253519       555
839         1840        8         16  42512.076447       555
24          1025        3         16  42394.666275       555
153         1154        8         19  41712.365313       555
272         1273       13         19  41628.905690       455
660         1661        5         16  40346.276266       555
924         1925       15         17  40255.320629       455

============================================================
INTERACTIVE PRODUCT ANALYSIS
============================================================

Dropdown(description='Product:', options=('All Products', 'Camera', 'Headphones', 'Keyboard', 'Laptop', 'Monit…

Output()

============================================================
INTERACTIVE COUNTRY ANALYSIS
============================================================

Dropdown(description='Country:', options=('All Countries', 'Australia', 'Canada', 'Germany', 'India', 'UK', 'U…

Output()

============================================================
CUSTOMER SEGMENT EXPLORER
============================================================

Dropdown(description='Segment:', options=('All Segments', 'At Risk', 'Champions', 'High Value At Risk', 'Lost …

Output()

============================================================
AUTOMATIC BUSINESS INSIGHTS
============================================================
Best Product    : Speaker
Best Country    : Germany
Best Category   : Electronics
Largest Segment : Regular Customers
============================================================
FINAL E-COMMERCE CUSTOMER INTELLIGENCE REPORT
============================================================

Total Revenue       : $22,779,760.07
Total Customers     : 1,000
Total Transactions  : 10,000
Total Units Sold    : 30,054
Average Order Value : $2,277.98

Best Product        : Speaker
Best Country        : Germany
Best Category       : Electronics
Largest Segment     : Regular Customers

Customer Intelligence Analysis Completed.
============================================================